##
#
##
version: '2.1'

services:

  webserver:
    image: "senseasim:0.0.1"
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
#      - ${PWD}/data:/data
      - /Users/rem/data:/data
    ports:
      - "6348:6348"
    entrypoint: Rscript --vanilla --default-packages=methods,utils,stats /opt/project/bin/senseasim --webserver

  bash:
    image: "senseasim:0.0.1"
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/data:/data
    ports:
      - "6348:6348"
    entrypoint: bash

  rsession:
    image: "senseasim:0.0.1"
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/data:/data
    ports:
      - "6348:6348"
